### ISSUE TITLE
Doc Bug: Doc says that globstar takes a directory while the code does not.

### ISSUE THREAD

**Issue by bmartin** [gflohr/File-Globstar#8]
The code for `File::Globstar::globstar` does not accept a directory even though the doc implies that it does. Instead, the second argument is `$flags` to be pushed to `bsd_glob`.

**Comment by gflohr** [comment]
Fixed.  Originally, I thought it would be a good idea to allow matching against other directories but apparently I had changed my mind.

Thanks for your contributions and sorry for taking so long to come back to them.
