### ISSUE TITLE
Bug: globstar fails on windows with directories containing dot

### ISSUE THREAD

**Issue by bmartin** [gflohr/File-Globstar#9]
On windows, if you have files named:

* `dir_1/file1.txt`
* `dir.2/file2.txt`

then `globstar('**/*.txt')` will find `dir_1/file1.txt` but will *not* find `dir.2/file2.txt`. This is because ultimately `_globstar` will call `bsd_glob('dir\\.2/*.txt')` which will not match anything.

You can fix this by exempting `.` from the hand-rolled `quotemeta()` embedded in `_globstar`:

```diff
-    # This is a quotemeta() that does not escape the slash and the
-    # colon.  Escaped slashes confuse bsd_glob() and escaping colons
+    # This is a quotemeta() that does not escape the slash, the
+    # colon, or period.  Escaped slashes confuse bsd_glob() and escaping colons
     # may make a full port to Windows harder.
-    $current =~ s{([\x00-\x2e\x3b-\x40\x5b-\x5e\x60\x7b-\x7f])}{\\$1}g;
+    $current =~ s{([\x00-\x2d\x3b-\x40\x5b-\x5e\x60\x7b-\x7f])}{\\$1}g;
     if ($directory ne '' && '/' ne substr $directory, -1, 1) {
         $current .= '/';
     }
```

**Comment by gflohr** [comment]
Fixed. Thanks for the patch.

For the records: The bug was not windows-specific.
